[Settings]

# 模板和输出文件
source_file = config/user_demo.txt
final_file = output/ipv4/user_result.m3u

# 高清过滤 + 去重
urls_limit = 1

# 开启组播源，关闭一些不必要的源
open_multicast = True
open_online_search = False
open_hotel = False
open_local = False
open_subscribe = False

# 组播源
multicast_region_list = config/rtp/浙江_电信.txt
