[Settings]

# 模板和输出文件
source_file = config/user_demo.txt
final_file = output/ipv4/user_result.m3u

# 去重
urls_limit = 1

# 开启组播源
open_multicast = True

# 关闭本地源、订阅源
open_local = False
open_subscribe = False

# 组播源
multicast_region_list = config/rtp/浙江_电信.txt
