[Settings]

# 模板文件路径
source_file = config/user_demo.txt
# 生成结果文件路径
final_file = output/user_result.m3u

# 单个频道接口数量
urls_limit = 2

# 开启组播源功能

# 关闭本地源功能
open_local = False
# 关闭订阅源功能
# open_subscribe = False


# 开启补偿机制模式，用于控制当频道接口数量不足时，自动将不满足条件（例如低于最小速率）但可能可用的接口添加至结果中，从而避免结果为空的情况
open_supply = False

# 接口最大分辨率，需要开启 open_filter_resolution 才能生效 | Maximum resolution of the interface, need to enable open_filter_resolution to take effect

# 生成结果中接口的协议类型；可选值: ipv4、ipv6、all | Protocol type of the interface in the generated result; Optional values: ipv4, ipv6, all
ipv_type = ipv4


# 开启 RTMP 推流功能，需要安装 FFmpeg，利用本地带宽提升接口播放体验；可选值: True, False | Enable RTMP push function, need to install FFmpeg, use local bandwidth to improve the interface playback experience; Optional values: True, False
open_rtmp = False
# 关闭测速
# open_speed_test = False
